# Generated by Django 4.2.9 on 2024-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_section_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='custom_index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
