# Generated by Django 4.2.9 on 2024-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_section_description_alter_dish_custom_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='custom_index',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
