# Generated by Django 4.2.9 on 2024-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_section_custom_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='media_file',
            field=models.FileField(default='default_value.mp4', upload_to='media/'),
        ),
    ]
