# Generated by Django 4.2.9 on 2024-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_blog_img_blog_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.FileField(default='default_value.mp4', upload_to='media/')),
                ('text', models.TextField()),
            ],
        ),
    ]
