# Generated by Django 4.2.9 on 2024-01-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_partyservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyservice',
            old_name='media_file',
            new_name='media_file_p',
        ),
        migrations.RenameField(
            model_name='partyservice',
            old_name='text',
            new_name='text_p',
        ),
        migrations.RenameField(
            model_name='partyservice',
            old_name='title',
            new_name='title_p',
        ),
    ]
