# Generated by Django 4.2.9 on 2024-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_media_file_partyservice_media_file_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyservice',
            name='title_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
