# Generated by Django 4.2.9 on 2024-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_dishgallery_alter_partyservice_title_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishgallery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partyservice',
            name='title_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
