# Generated by Django 4.2.9 on 2024-01-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.TextField()),
                ('contact_us', models.TextField()),
                ('internet', models.TextField()),
                ('telephone', models.TextField()),
            ],
        ),
    ]
